# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_signum')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_signum')
    _signum = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_signum', [dirname(__file__)])
        except ImportError:
            import _signum
            return _signum
        try:
            _mod = imp.load_module('_signum', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _signum = swig_import_helper()
    del swig_import_helper
else:
    import _signum
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x



def signum_calc(n):
    return _signum.signum_calc(n)
signum_calc = _signum.signum_calc

def global_callback(ptr):
    return _signum.global_callback(ptr)
global_callback = _signum.global_callback

def triggerCallback():
    return _signum.triggerCallback()
triggerCallback = _signum.triggerCallback
class Register(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Register, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Register, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _signum.new_Register()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _signum.delete_Register
    __del__ = lambda self: None

    def addEntry(self, arg2):
        return _signum.Register_addEntry(self, arg2)

    def getEntry(self, i):
        return _signum.Register_getEntry(self, i)
Register_swigregister = _signum.Register_swigregister
Register_swigregister(Register)

class ICallback(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ICallback, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ICallback, name)
    __repr__ = _swig_repr

    def Call(self):
        return _signum.ICallback_Call(self)
    __swig_destroy__ = _signum.delete_ICallback
    __del__ = lambda self: None

    def __init__(self):
        if self.__class__ == ICallback:
            _self = None
        else:
            _self = self
        this = _signum.new_ICallback(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _signum.disown_ICallback(self)
        return weakref_proxy(self)
ICallback_swigregister = _signum.ICallback_swigregister
ICallback_swigregister(ICallback)

class Example(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Example, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Example, name)
    __repr__ = _swig_repr

    def GiveCallback(self, callback):
        return _signum.Example_GiveCallback(self, callback)

    def CallCallback(self):
        return _signum.Example_CallCallback(self)
    __swig_setmethods__["callback_"] = _signum.Example_callback__set
    __swig_getmethods__["callback_"] = _signum.Example_callback__get
    if _newclass:
        callback_ = _swig_property(_signum.Example_callback__get, _signum.Example_callback__set)

    def __init__(self):
        this = _signum.new_Example()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _signum.delete_Example
    __del__ = lambda self: None
Example_swigregister = _signum.Example_swigregister
Example_swigregister(Example)

# This file is compatible with both classic and new-style classes.


